spring.application.name=WeatherRestAPI
bh.api.url=https://api.open-meteo.com/v1/forecast?latitude=-19.9167&longitude=-43.9345&current=temperature_2m
openmeteo.api.url=https://geocoding-api.open-meteo.com/v1/search?name=
server.port=8080
